CREATE TRIGGER [dbo].[TRG_CARGA_DA1] ON [dbo].[DA1010] 
FOR INSERT, UPDATE
AS 
BEGIN
	DECLARE @RECNO INT, @NREG INT, @DATA INT, @HORA varchar(08), @TB VARCHAR(03), @LOJA VARCHAR(06)
	SELECT 
		@HORA  = SUBSTRING(CONVERT(VARCHAR,SYSDATETIME()),12,8)
		, @DATA  = CONVERT(VARCHAR(8), GETDATE(), 112)
		, @TB = 'DA1'
	
	DECLARE CurIns CURSOR FAST_FORWARD FOR
	select  DA1_FILIAL, R_E_C_N_O_ from INSERTED WHERE DA1_CODTAB = '001' --CODIGO DA TABELA DE PRECOS QUE QUERO MARCAR PARA EXPORTAR
	OPEN CurIns
	FETCH NEXT FROM CurIns INTO @LOJA, @NREG

	WHILE @@FETCH_STATUS = 0
	BEGIN
		SELECT @RECNO = (SELECT ISNULL(MAX(R_E_C_N_O_),1)+1 FROM ZZ0010)

		IF NOT EXISTS( SELECT * FROM ZZ0010 WHERE ZZ0_FILIAL= @LOJA AND ZZ0_TABELA= @TB AND ZZ0_NREG = @NREG )
			INSERT ZZ0010 (ZZ0_FILIAL, ZZ0_TABELA, ZZ0_NREG, ZZ0_DATA, ZZ0_HORA, D_E_L_E_T_, R_E_C_N_O_) 
			VALUES (            @LOJA,        @TB,    @NREG,    @DATA,    @HORA,        ' ',    @RECNO ) 
		ELSE
			UPDATE ZZ0010 SET 
			  ZZ0_DATA = @DATA
			, ZZ0_HORA = @HORA
			WHERE 
					ZZ0_TABELA = @TB
				AND ZZ0_NREG   = @NREG
				AND ZZ0_FILIAL = @LOJA
		FETCH NEXT FROM CurIns INTO @LOJA, @NREG
	END
	CLOSE CurIns
	DEALLOCATE CurIns
END